name: build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        path: .

    - name: Donwload dependencies
      run: |
        Invoke-WebRequest https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-win64.zip -OutFile nasm.zip
        Invoke-WebRequest https://deac-riga.dl.sourceforge.net/project/gnuwin32/grep/2.5.4/grep-2.5.4-bin.zip -OutFile grep.zip
        Invoke-WebRequest https://master.dl.sourceforge.net/project/gnuwin32/grep/2.5.4/grep-2.5.4-dep.zip?viasf=1 -OutFile grep-dep.zip
        mkdir nasm
        mkdir grep
        unzip nasm.zip nasm-2.16.01/nasm.exe -d nasm
        unzip grep.zip bin/grep.exe -d grep
        unzip grep-dep.zip bin/* -d grep
        mv grep/bin/* .
        mv nasm/nasm-2.16.01/nasm.exe ./nasm.exe

    - name: Assemble injections
      shell: cmd
      run: |
        mkdir bin
        make src/inc/injections.inc
